name: 网页更新

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '30 13 * * *'  # 每天21:30:00执行一次

jobs:
  # 任务1：交易时间条件检查
  check:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check_time.outputs.result }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run trading day AND time checker
        id: check_time
        # 如果是手动触发，直接输出 true；否则执行检查
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "result=true" >> $GITHUB_OUTPUT
          else
            echo "result=$(python check_trading.py)" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check
    if: needs.check.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'  # 设置时区为上海

    steps:
      # Checkout main branch to get the latest code
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: main  # Checkout main branch

      - name: Set timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV

      # update display for 1d schedule
      - name: update display
        env:
          SQL_PASSWORDS: ${{ secrets.SQL_PASSWORDS }}
          SQL_HOST: ${{ secrets.SQL_HOST }}
        run: |
          pip install -r ./requirements.txt
          python3 ./fetch_special_holidays.py
          python3 ./display_bench_stats.py

      - name: Git config and commit
        run: |
          git config --global user.email "ouweijie123@outlook.com"
          git config --global user.name "update actioner"
          git add .
          git commit -m "update_${{ env.timestamp }}" || echo "No changes to commit"

      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          branch: main